import type { SnapshotDocument } from "./types";

export function createTestSnapshot(overrides: Partial<SnapshotDocument> = {}): SnapshotDocument {
  return {
    schemaVersion: "jip-v1",
    snapshotLabel: "test-snapshot",
    generatedAt: "20260328-170000",
    clockResolution: "ns",
    summary: {
      threadCount: 2,
      interactionCount: 3,
      frameCount: 5,
      allocationClassCount: 1,
      totalObservedTimeNanos: 10_000_000,
    },
    timeline: {
      bucketSizeMs: 1000,
      durationNanos: 10_000_000,
      jfrBucketSizeMs: 0,
      buckets: [
        {
          bucketIndex: 0,
          startOffsetMs: 0,
          endOffsetMs: 1000,
          observedTimeNanos: 10_000_000,
          eventCount: 3,
          activeThreadCount: 2,
          topThreads: [],
        },
      ],
      threads: [
        {
          threadId: 1,
          observedTimeNanos: 8_000_000,
          eventCount: 2,
          peakBucketIndex: 0,
          peakStartOffsetMs: 0,
          peakEndOffsetMs: 1000,
          peakObservedTimeNanos: 8_000_000,
        },
      ],
      jfrBuckets: [],
    },
    threads: [
      {
        threadId: 1,
        totalTimeNanos: 8_000_000,
        interactions: [
          {
            name: "sample.Service:run",
            className: "sample.Service",
            methodName: "run",
            count: 1,
            totalTimeNanos: 8_000_000,
            netTimeNanos: 5_000_000,
            children: [
              {
                name: "sample.Worker:step",
                className: "sample.Worker",
                methodName: "step",
                count: 1,
                totalTimeNanos: 3_000_000,
                netTimeNanos: 3_000_000,
                children: [],
              },
            ],
          },
        ],
      },
    ],
    topMethods: [
      {
        name: "sample.Service:run",
        className: "sample.Service",
        methodName: "run",
        count: 1,
        totalTimeNanos: 8_000_000,
        netTimeNanos: 5_000_000,
      },
      {
        name: "sample.Worker:step",
        className: "sample.Worker",
        methodName: "step",
        count: 1,
        totalTimeNanos: 3_000_000,
        netTimeNanos: 3_000_000,
      },
    ],
    methodSummary: [
      {
        name: "sample.Service:run",
        className: "sample.Service",
        methodName: "run",
        count: 1,
        totalTimeNanos: 8_000_000,
        netTimeNanos: 5_000_000,
      },
      {
        name: "sample.Worker:step",
        className: "sample.Worker",
        methodName: "step",
        count: 1,
        totalTimeNanos: 3_000_000,
        netTimeNanos: 3_000_000,
      },
    ],
    allocations: [
      {
        className: "sample.Widget",
        internalClassName: "sample/Widget",
        count: 5,
        jfrSampleCount: 0,
        jfrSampleBytes: 0,
      },
    ],
    jfr: {
      enabled: false,
      artifact: "",
      warning: "",
      metadata: {
        samplePeriodMs: 0,
        executionSamplingEnabled: false,
        nativeSamplingEnabled: false,
        cpuTimeSamplingEnabled: false,
        allocationEventsEnabled: false,
        monitorEnterEventsEnabled: false,
        monitorWaitEventsEnabled: false,
        threadParkEventsEnabled: false,
      },
      executionSampleCount: 0,
      nativeSampleCount: 0,
      cpuTimeSampleCount: 0,
      allocationSampleCount: 0,
      monitorEnterCount: 0,
      monitorWaitCount: 0,
      threadParkCount: 0,
      contentionEventCount: 0,
      contentionDurationNanos: 0,
      topSampledMethods: [],
      topAllocationSamples: [],
      topAllocationPaths: [],
      topContentionSamples: [],
    },
    asyncProfiler: {
      enabled: false,
      warning: "",
      artifacts: [],
      collapsed: { file: "", totalSamples: 0, topLeafFrames: [], topStacks: [] },
    },
    insights: [
      {
        type: "dominant-hotspot",
        severity: "high",
        title: "Dominant hotspot",
        summary: "sample.Service:run dominates the profile",
        evidence: ["sample.Service:run accounts for 50% of net time"],
      },
    ],
    history: {
      enabled: false,
      indexArtifact: "",
      current: null,
      entries: [],
    },
    artifacts: {
      basePath: "/tmp/test",
      json: "/tmp/test.json",
      html: "/tmp/test.html",
      jfr: "",
      recordingIndex: "",
    },
    ...overrides,
  };
}
